Added basic support for interrupt handlers
kawamuray/wasmtime-java pull request #26
Opened 2021-12-18 00:20 UTC by lbenard

Basic support for interrupt handlers. The `Store` can create the interrupt handler by itself so I changed the constructor to take an already existing ptr

2021-12-19 10:55 UTC, kawamuray requested changes
Thanks for the PR! Left few comments.

2021-12-19 10:55 UTC, kawamuray commented on wasmtime-jni/src/io_github_kawamuray_wasmtime_Store/imp.rs
> +        let interrupt_handle = store.interrupt_handle()?;
Currently this value never dropped anywhere, which will cause memory leak.
We have to implement `Disposable` to `InterruptHandle` class and implement `dispose()` methods like other classes.

2021-12-19 17:22 UTC, lbenard commented
Should be good, let me know if there's anything else missing!

2021-12-20 01:05 UTC, kawamuray approved these changes
LGTM, thanks!

2021-12-20 01:05 UTC, merged