Use Ubuntu 18.04 to link against an older versions of glibc for compatibility
kawamuray/wasmtime-java pull request #49
Opened 2023-06-19 18:27 UTC by rob-odwyer

The current published JNI build requires glibc >= 2.32 to be installed, otherwise you get this error:
```
java.lang.UnsatisfiedLinkError: /tmp/libwasmtime_jni_0.14.0_linux12559640904482558164.so: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/libwasmtime_jni_0.14.0_linux12559640904482558164.so)
```
From our testing, we've found that just building against an older version of glibc will result in a more compatible build, since later installs will still include support for the older glibc versions. The easiest way to do that is to use the older `ubuntu-18.04` runner, which will result in linking against `GLIBC_2.27`. I've included a debug step here to show that, but I'm happy to remove it if required.

I've tested this out myself via a local actions runner and it doesn't seem to introduce any incompatibilities. In order to actually depend on the resulting build from our library however, it's much simpler to have a new release made from this project, instead of a manually included JAR.

2023-06-19 23:14 UTC, kawamuray requested changes
Hi @rob-odwyer , thanks for the PR!

I think using older ubuntu for supporting more glibc is fine, so please fix the CI failure to get this in.

2023-06-19 23:14 UTC, kawamuray commented on .github/workflows/ci.yml
> +      run: nm -D /lib/x86_64-linux-gnu/libc.so.6 | grep " GLIBC_2" | sort -V
This doesn't run on platform other than linux and causing CI fail on macos, windows now so we need branching based on the running platform or just remove this line.

2023-06-21 01:51 UTC, kawamuray approved these changes
LGTM, thanks!

2023-06-21 21:16 UTC, rob-odwyer commented
I've updated to use Ubuntu 20.04, which hopefully won't already be deprecated by the time the workflow runs.

2023-06-22 00:02 UTC, kawamuray commented
CI with the previous commit didn't start actually: https://github.com/kawamuray/wasmtime-java/actions/runs/5324587129/jobs/9654650389

2023-06-22 12:53 UTC, merged

2023-07-28 16:29 UTC, rob-odwyer commented
@luckoseabraham Looks like the second gradle build in the publish step actually re-generates the linux shared lib, which replaces the compatible one from the build step.
I'm working on another change that fixes this along with improving the GLIBC compatibility further, will keep you posted.

2023-07-28 20:27 UTC, rob-odwyer commented
@luckoseabraham I believe this PR should fix the issue:
https://github.com/kawamuray/wasmtime-java/pull/50
and I've tested the shared lib that actually ends up inside the JAR this time 😄

2023-07-28 20:54 UTC, luckoseabraham commented
That's awesome @rob-odwyer. Thank you !